name: Download from yande.re (with limit)

on:
  workflow_dispatch:
    inputs:
      LIMIT:
        description: 'LIMIT'
        required: true
      TAG:
        description: 'TAG'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: booru

      - name: Configure Git
        run: |
          git config --global user.email "parsastdev@duck.com"
          git config --global user.name "Parsast"

      - name: Download from Booru
        run: curl -s "https://yande.re/post.json?limit=${{ github.event.inputs.LIMIT }}&tags=${{ github.event.inputs.TAG }}" | jq -r '.[].jpeg_url' | aria2c -i-

      - name: Push Booru Files to Repo
        run: |
          git add -A
          git commit -m "push booru files to repo"
          git push -u origin booru
