name: Download from yande.re

on:
  workflow_dispatch:
    inputs:
      ID:
        description: 'ID'
        required: true

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: booru

      - name: Configure Git
        run: |
          git config --global user.email "parsastdev@duck.com"
          git config --global user.name "Parsast"

      - name: Download from Booru
        run: curl -s "https://yande.re/post.json?tags=id:${{ github.event.inputs.ID }}" | jq -r '.[].jpeg_url' | aria2c -i-

      - name: Push Booru Files to Repo
        run: |
          git add -A
          git commit -m "push booru files to repo"
          git push -u origin booru
