name: Download Releases

on:
  workflow_dispatch:
    inputs:
      GITHUB_REPO:
        description: 'GITHUB_REPO'
        required: true
        default: 'amir1376/ab-download-manager'
      VERSION:
        description: 'VERSION'
        required: true
      FILE_NAME:
        description: 'FILE_NAME'
        required: true

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "parsastdev@duck.com"
          git config --global user.name "Parsast"

      - name: Push Release to Repo
        run: |
          aria2c https://github.com/${{ github.event.inputs.GITHUB_REPO }}/releases/download/${{ github.event.inputs.VERSION }}/${{ github.event.inputs.FILE_NAME }}
          git add -A
          git commit -m "push release to repo"
          git push -u origin main
